version: '2'
services:
  nso:
    image: chapeter/docker-nso
    build: .
    volumes:
      - ./nso:/tmp/nso
      - ./ncs-run:/opt/ncs-run
      - ./neds:/tmp/neds
    ports:
      - 2024:2024
      - 8080:8080
      - 2022:2022
    command: "./run.sh"
